database:
  default:
    type:   'mysql'
    host:   'xxx'
    port:   '22649'
    user:   'root'
    pass:   'xxx'
    name:   'chess'
    timezone:   'Local'
    maxIdle:    '30'
    maxOpen:    '300'
    maxLifetime:    '30s'
redis:
  default:
    address:    'xxx'
    pass:       'xxx'
    db:         4
    minIdle:    0
    MaxIdle:    100
    maxActive:  10000
    idleTimeout: "30s"
    maxConnLifetime: "3m"
    waitTimeout: "30s"
    dialTimeout: "30s"
    readTimeout: "30s"
    writeTimeout: "30s"